<a href="https://colab.research.google.com/github/QuinAmii/-content-Queen-Echerenwa-Data-Science-Assignment/blob/main/Week_3_Assignment_Queen_Echerenwa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Create 2 different array (x and y) from a list
import numpy as np
arr_x = np.array([[13, 16, 19], [10, 20, 30]])
arr_y = np.array([[12, 22, 32], [18, 28, 38]])

print("Array X")
print(arr_x, '\n')

print("Array Y")
print(arr_y, '\n')

Array X
[[13 16 19]
 [10 20 30]] 

Array Y
[[12 22 32]
 [18 28 38]] 



In [ ]:
#Add array x and y print result
print("Direct Addition")
print (arr_x + arr_y, '\n')

Direct Addition
[[25 38 51]
 [28 48 68]] 



In [ ]:
#Subtract array x and y print result 
print (arr_x - arr_y, '\n')

[[  1  -6 -13]
 [ -8  -8  -8]] 



In [ ]:
#Multiply array x by 5 print result
print("Direct Multiplication")
print (arr_x * 5, '\n')

Direct Multiplication
[[ 65  80  95]
 [ 50 100 150]] 



In [ ]:
#Divide array y by 10 print result
print("Direct Division")
print (arr_x / 10, '\n')

Direct Division
[[1.3 1.6 1.9]
 [1.  2.  3. ]] 



In [ ]:
#Creating from a list of lists
pet_info = [['Howard', 10, 'Goat'], ['Lucy', 4 , 'Fish'], ['Roco', 8, 'Lizard']]
pet_info

[['Howard', 10, 'Goat'], ['Lucy', 4, 'Fish'], ['Roco', 8, 'Lizard']]

In [ ]:
import pandas as pd
pet_df = pd.DataFrame(pet_info, columns = ['Name', 'Age', 'Type'],
                      index = ['A', 'B', 'C'])
pet_df
                     

Name  Age    Type
A  Howard   10    Goat
B    Lucy    4    Fish
C    Roco    8  Lizard

In [ ]:
pet_df.iloc[0]

Name    Howard
Age         10
Type      Goat
Name: A, dtype: object

In [ ]:
pet_df.iloc[1]

Name    Lucy
Age        4
Type    Fish
Name: B, dtype: object

In [ ]:
pet_df.iloc[2]

Name      Roco
Age          8
Type    Lizard
Name: C, dtype: object

In [2]:
import numpy as np
import pandas as pd

In [5]:
df=pd.read_csv('/weight-height.csv')

In [24]:
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [26]:
#Please i don't have a fifth datapoint, i will be working with the fourth bare with me.
df.iloc[4]

Gender       Male
Height    69.8818
Weight     206.35
Name: 4, dtype: object

In [22]:
df[['Height']] 

Height
0     73.847017
1     68.781904
2     74.110105
3     71.730978
4     69.881796
...         ...
9995  66.172652
9996  67.067155
9997  63.867992
9998  69.034243
9999  61.944246

[10000 rows x 1 columns]